apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ra7pfbmvg-nodejs 
  janus-idp.io/tekton: ra7pfbmvg-nodejs
  backstage.io/kubernetes-id: ra7pfbmvg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ra7pfbmvg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  